from __future__ import annotations

import unittest
from unittest.mock import patch

from custerion_collection.artifact_builder import build_deep_dive_artifact


class TestArtifactBuilder(unittest.TestCase):
    def setUp(self) -> None:
        self._fallback_patcher = patch(
            "custerion_collection.artifact_builder._llm_section_fallbacks",
            return_value={},
        )
        self._fallback_patcher.start()

    def tearDown(self) -> None:
        self._fallback_patcher.stop()

    def test_build_artifact_parses_sections_and_bounds_media(self) -> None:
        markdown = """
## Personalized Intro
Why this film now for you.

## History
Grounded in post-war ballet culture.

## Craft
Cinematography emphasizes expressive color.

## Industry
Successful release and long-tail acclaim.

## Notable Lore
Famously influenced later directors.

## What To Watch Next
- Black Narcissus
- The Tales of Hoffmann

## Known Unknowns
- Box-office split by region is uncertain.

## Follow-Up Media
1. Wikipedia article: https://en.wikipedia.org/wiki/The_Red_Shoes_(film)
2. Video essay: https://www.youtube.com/watch?v=abc123
3. Related film: https://www.themoviedb.org/movie/1
""".strip()

        artifact = build_deep_dive_artifact("Blade Runner (1982) (1948)", markdown)

        self.assertEqual(artifact.film.title, "Blade Runner (1982)")
        self.assertEqual(artifact.film.year, 1948)
        self.assertEqual([section.name for section in artifact.sections], ["History", "Craft", "Industry", "Notable Lore"])
        self.assertGreaterEqual(len(artifact.watch_next), 2)
        self.assertGreaterEqual(len(artifact.known_unknowns), 1)
        self.assertEqual(len(artifact.follow_up_media), 3)
        self.assertLessEqual(len(artifact.follow_up_media), 8)
        self.assertGreaterEqual(len(artifact.citations), 3)

    def test_build_artifact_ignores_placeholder_source_domains(self) -> None:
        markdown = """
## Personalized Intro
Quick setup.

## History
Reference placeholder: https://example.com/fake-source

## Follow-Up Media
1. Placeholder article: https://example.com/reference
2. Valid article: https://en.wikipedia.org/wiki/Blade_Runner
""".strip()

        artifact = build_deep_dive_artifact("Blade Runner (1982)", markdown)

        urls = [str(item.url) for item in artifact.follow_up_media if item.url is not None]
        citations = [str(item.url) for item in artifact.citations if item.url is not None]

        self.assertIn("https://en.wikipedia.org/wiki/Blade_Runner", urls)
        self.assertNotIn("https://example.com/reference", urls)
        self.assertNotIn("https://example.com/fake-source", citations)

    def test_build_artifact_parses_guided_commentary_timestamps(self) -> None:
        markdown = """
## Guided Commentary Timeline
- [00:42] Opening alleyway :: Rain and neon create immediate noir tension.
- [01:15] Detective briefing :: Dialogue anchors the existential mystery.
""".strip()

        artifact = build_deep_dive_artifact("Blade Runner (1982)", markdown)

        self.assertEqual(artifact.commentary_mode, "timed")
        self.assertEqual(len(artifact.commentary_segments), 2)
        self.assertEqual(artifact.commentary_segments[0].timestamp_ms, 42000)
        self.assertEqual(artifact.commentary_segments[1].timestamp_ms, 75000)

    def test_build_artifact_retains_untimed_commentary_lines(self) -> None:
        markdown = """
## Guided Commentary Timeline
- Rooftop pursuit :: Movement and score escalate urgency.
- Quiet apartment scene :: Light and framing stress emotional distance.
""".strip()

        artifact = build_deep_dive_artifact("Blade Runner (1982)", markdown)

        self.assertEqual(artifact.commentary_mode, "untimed")
        self.assertEqual(len(artifact.commentary_segments), 2)
        self.assertIsNone(artifact.commentary_segments[0].timestamp_ms)

    @patch(
        "custerion_collection.artifact_builder._llm_section_fallbacks",
        return_value={
            "Industry": (
                "LLM-only fallback: this section is entirely generated by the Trivia LLM provider, "
                "without verified search sources, and details may be hallucinated.\n\n"
                "Industry context inferred from broad release patterns and critical discourse."
            )
        },
    )
    def test_build_artifact_uses_llm_fallback_for_missing_sections(self, _mock_fallback) -> None:
        markdown = """
## Personalized Intro
Quick setup.

## History
Grounded context.

## Craft
Visual analysis.

## Notable Lore
Interesting production anecdotes.
""".strip()

        artifact = build_deep_dive_artifact("Blade Runner (1982)", markdown)
        industry = next(section for section in artifact.sections if section.name == "Industry")

        self.assertIn("LLM-only fallback", industry.content)
        self.assertIn("may be hallucinated", industry.content)

    @patch(
        "custerion_collection.artifact_builder._llm_section_fallbacks",
        return_value={
            "Industry": (
                "LLM-only fallback: this section is entirely generated by the Trivia LLM provider, "
                "without verified search sources, and details may be hallucinated.\n\n"
                "Industry context generated after research-provider failure."
            )
        },
    )
    def test_build_artifact_replaces_failed_research_section_with_llm_fallback(self, _mock_fallback) -> None:
        markdown = """
## Personalized Intro
Quick setup.

## History
Grounded context.

## Craft
Visual analysis.

## Industry
TMDb industry lookup failed for 'Blade Runner (1982)': HTTP 503.

## Notable Lore
Interesting production anecdotes.
""".strip()

        artifact = build_deep_dive_artifact("Blade Runner (1982)", markdown)
        industry = next(section for section in artifact.sections if section.name == "Industry")

        self.assertIn("LLM-only fallback", industry.content)
        self.assertNotIn("TMDb industry lookup failed", industry.content)


if __name__ == "__main__":
    unittest.main()